# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("//loom/build_tools/bazel:defs.bzl", "loom_test", "loom_test_module")
load("//loom/target/vm:execution_profiles.bzl", "VM_REFERENCE_PROFILE")

package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

_SOURCES = glob(["*.loom"])

exports_files(_SOURCES)

loom_test(
    name = "vm_test",
    execution_profiles = [VM_REFERENCE_PROFILE],
    module = ":functions",
)

loom_test_module(
    name = "functions",
    srcs = _SOURCES,
)
