# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# Shared sanitizer suppression helpers for CTest rules.

include_guard(GLOBAL)

include("${CMAKE_CURRENT_LIST_DIR}/../cmake/iree_test_arguments.cmake")

set(IREE_SANITIZER_SUPPRESSION_HSA_LSAN
  "${CMAKE_CURRENT_LIST_DIR}/lsan_suppressions_hsa.txt")
set(IREE_SANITIZER_SUPPRESSION_ROCM_LSAN
  "${CMAKE_CURRENT_LIST_DIR}/lsan_suppressions_rocm.txt")
set(IREE_SANITIZER_SUPPRESSION_VULKAN_LSAN
  "${CMAKE_CURRENT_LIST_DIR}/lsan_suppressions_vulkan.txt")

function(iree_sanitizer_suppression_file OUTPUT_VARIABLE SANITIZER NAME)
  string(TOLOWER "${SANITIZER}" _SANITIZER_LOWER)
  if(NOT _SANITIZER_LOWER MATCHES "^(asan|lsan|msan|tsan|ubsan)$")
    message(FATAL_ERROR "unknown sanitizer suppression kind: ${SANITIZER}")
  endif()
  string(TOUPPER "${SANITIZER}" _SANITIZER_UPPER)
  string(TOUPPER "${NAME}" _NAME_UPPER)
  set(_VARIABLE_NAME "IREE_SANITIZER_SUPPRESSION_${_NAME_UPPER}_${_SANITIZER_UPPER}")
  if(NOT DEFINED ${_VARIABLE_NAME})
    message(FATAL_ERROR
      "unknown sanitizer suppression '${SANITIZER}=${NAME}'")
  endif()
  set(${OUTPUT_VARIABLE} "${${_VARIABLE_NAME}}" PARENT_SCOPE)
endfunction()

# Dependency metadata is resolved once all targets exist. Test properties refer
# to the result through a generator expression, so declaration order is immaterial.
function(iree_target_sanitizer_suppressions TARGET_NAME)
  cmake_parse_arguments(_RULE "" "" "DEPS;SUPPRESSIONS;ENV" ${ARGN})
  set_property(TARGET "${TARGET_NAME}" PROPERTY
    IREE_SANITIZER_DEPENDENCIES "${_RULE_DEPS}")
  set_property(TARGET "${TARGET_NAME}" PROPERTY IREE_SANITIZER_EXPLICIT_ENV "${_RULE_ENV}")
  set(_FILES)
  set(_PAIRS ${_RULE_SUPPRESSIONS})
  list(LENGTH _PAIRS _PAIR_LENGTH)
  math(EXPR _ODD "${_PAIR_LENGTH} % 2")
  if(_ODD)
    message(FATAL_ERROR "sanitizer suppressions must be SANITIZER NAME pairs")
  endif()
  while(_PAIRS)
    list(POP_FRONT _PAIRS _SANITIZER _NAME)
    iree_sanitizer_suppression_file(_FILE "${_SANITIZER}" "${_NAME}")
    string(TOLOWER "${_SANITIZER}" _SANITIZER)
    list(APPEND _FILES "${_SANITIZER}=${_FILE}")
  endwhile()
  set_property(TARGET "${TARGET_NAME}" PROPERTY IREE_SANITIZER_FILES "${_FILES}")
  set_property(GLOBAL APPEND PROPERTY IREE_SANITIZER_TARGETS "${TARGET_NAME}")
endfunction()

function(_iree_collect_sanitizer_suppressions OUTPUT_VARIABLE TARGET_NAME)
  _iree_resolve_target(_TARGET "${TARGET_NAME}")
  if(NOT _TARGET)
    set(${OUTPUT_VARIABLE} "" PARENT_SCOPE)
    return()
  endif()
  get_property(_RESOLVED TARGET "${_TARGET}" PROPERTY IREE_SANITIZER_RESOLVED)
  if(_RESOLVED)
    get_property(_FILES TARGET "${_TARGET}" PROPERTY IREE_SANITIZER_TRANSITIVE_FILES)
    set(${OUTPUT_VARIABLE} "${_FILES}" PARENT_SCOPE)
    return()
  endif()
  get_property(_VISITING TARGET "${_TARGET}" PROPERTY IREE_SANITIZER_VISITING)
  if(_VISITING)
    message(FATAL_ERROR "Cyclic sanitizer dependency at ${_TARGET}")
  endif()
  set_property(TARGET "${_TARGET}" PROPERTY IREE_SANITIZER_VISITING ON)
  get_property(_FILES TARGET "${_TARGET}" PROPERTY IREE_SANITIZER_FILES)
  get_property(_DEPENDENCIES TARGET "${_TARGET}" PROPERTY IREE_SANITIZER_DEPENDENCIES)
  foreach(_DEPENDENCY IN LISTS _DEPENDENCIES)
    # These interfaces are unconditional within the build tree. Configuration
    # selection in generated DEPS has already been resolved by its CMake guard.
    if(_DEPENDENCY MATCHES "^\\$<BUILD_(LOCAL_)?INTERFACE:([^<>]+)>$")
      set(_DEPENDENCY "${CMAKE_MATCH_2}")
    endif()
    if(_DEPENDENCY MATCHES "\\$<")
      message(FATAL_ERROR "Sanitizer dependency must be configured before registration: ${_DEPENDENCY}")
    endif()
    _iree_collect_sanitizer_suppressions(_DEPENDENCY_FILES "${_DEPENDENCY}")
    list(APPEND _FILES ${_DEPENDENCY_FILES})
  endforeach()
  list(REMOVE_DUPLICATES _FILES)
  list(SORT _FILES)
  set_property(TARGET "${_TARGET}" PROPERTY IREE_SANITIZER_VISITING OFF)
  set_property(TARGET "${_TARGET}" PROPERTY IREE_SANITIZER_RESOLVED ON)
  set_property(TARGET "${_TARGET}" PROPERTY IREE_SANITIZER_TRANSITIVE_FILES "${_FILES}")
  set(${OUTPUT_VARIABLE} "${_FILES}" PARENT_SCOPE)
endfunction()

function(iree_finalize_sanitizer_suppressions)
  get_property(_TARGETS GLOBAL PROPERTY IREE_SANITIZER_TARGETS)
  foreach(_TARGET IN LISTS _TARGETS)
    _iree_collect_sanitizer_suppressions(_FILES "${_TARGET}")
    get_property(_EXPLICIT_ENV TARGET "${_TARGET}" PROPERTY IREE_SANITIZER_EXPLICIT_ENV)
    set(_ENVIRONMENT)
    set(_ENVIRONMENT_ARGUMENTS)
    foreach(_SANITIZER asan lsan msan tsan ubsan)
      set(_INPUTS)
      foreach(_ENTRY IN LISTS _FILES)
        if(_ENTRY MATCHES "^${_SANITIZER}=(.+)$")
          list(APPEND _INPUTS "${CMAKE_MATCH_1}")
        endif()
      endforeach()
      if(NOT _INPUTS)
        continue()
      endif()
      list(LENGTH _INPUTS _INPUT_COUNT)
      if(_INPUT_COUNT EQUAL 1)
        set(_OUTPUT "${_INPUTS}")
      else()
        string(SHA256 _KEY "${_SANITIZER};${_INPUTS}")
        set(_OUTPUT "${CMAKE_BINARY_DIR}/sanitizer/${_KEY}.${_SANITIZER}.txt")
        get_property(_WRITTEN GLOBAL PROPERTY "IREE_SANITIZER_MERGED_${_KEY}")
        if(NOT _WRITTEN)
          set(_CONTENT "")
          foreach(_INPUT IN LISTS _INPUTS)
            set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_INPUT}")
            file(READ "${_INPUT}" _INPUT_CONTENT)
            string(APPEND _CONTENT "${_INPUT_CONTENT}\n")
          endforeach()
          file(CONFIGURE OUTPUT "${_OUTPUT}" CONTENT "@_CONTENT@" @ONLY)
          set_property(GLOBAL PROPERTY "IREE_SANITIZER_MERGED_${_KEY}" ON)
        endif()
      endif()
      string(TOUPPER "${_SANITIZER}" _UPPER)
      set(_OPTIONS "suppressions=\"{{${_OUTPUT}}}\"")
      if(_SANITIZER STREQUAL "lsan")
        string(APPEND _OPTIONS ":allow_addr2line=1")
      endif()
      list(APPEND _ENVIRONMENT_ARGUMENTS "${_UPPER}_OPTIONS=${_OPTIONS}")
      iree_resolve_test_arguments(_OPTIONS _OPTION_FILES
        iree_build_test_file_argument "${_OPTIONS}")
      foreach(_ENTRY IN LISTS _EXPLICIT_ENV)
        if(_ENTRY MATCHES "^${_UPPER}_OPTIONS=" AND
           NOT _ENTRY STREQUAL "${_UPPER}_OPTIONS=${_OPTIONS}")
          message(FATAL_ERROR "${_TARGET} sets ${_UPPER}_OPTIONS both explicitly and through sanitizer dependencies")
        endif()
      endforeach()
      list(APPEND _ENVIRONMENT "${_UPPER}_OPTIONS=${_OPTIONS}")
    endforeach()
    set_property(TARGET "${_TARGET}" PROPERTY IREE_SANITIZER_ENVIRONMENT "${_ENVIRONMENT}")
    set_property(TARGET "${_TARGET}" PROPERTY IREE_SANITIZER_ENVIRONMENT_ARGUMENTS "${_ENVIRONMENT_ARGUMENTS}")
  endforeach()
endfunction()
