# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("//runtime/build_tools/bazel:cc.bzl", "iree_runtime_cc_library")
load("//runtime/build_tools/bazel:cc_fuzz.bzl", "iree_runtime_cc_fuzz")
load("//runtime/build_tools/bazel:cc_test.bzl", "iree_runtime_cc_test")

package(
    default_visibility = ["//visibility:public"],
    features = ["layering_check"],
    licenses = ["notice"],  # Apache 2.0
)

iree_runtime_cc_library(
    name = "bulk_channel",
    srcs = ["bulk_channel.c"],
    hdrs = ["bulk_channel.h"],
    deps = [
        "//runtime/src/iree/async",
        "//runtime/src/iree/base",
        "//runtime/src/iree/base:core_headers",
        "//runtime/src/iree/base/internal",
        "//runtime/src/iree/net:message_endpoint",
    ],
)

iree_runtime_cc_test(
    name = "bulk_channel_test",
    srcs = ["bulk_channel_test.cc"],
    deps = [
        ":bulk_channel",
        "//runtime/src/iree/async",
        "//runtime/src/iree/base",
        "//runtime/src/iree/base:core_headers",
        "//runtime/src/iree/net:message_endpoint",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
    ],
)

iree_runtime_cc_fuzz(
    name = "bulk_channel_fuzz",
    srcs = ["bulk_channel_fuzz.cc"],
    deps = [
        ":bulk_channel",
        "//runtime/src/iree/async",
        "//runtime/src/iree/base",
        "//runtime/src/iree/net:message_endpoint",
    ],
)
