# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# bazel-to-cmake: skip

load("@hrx//loom/build_tools/bazel:defs.bzl", "loom_execution_profile", "loom_kernel_library", "loom_library", "loom_test")
load("@hrx//loom/requirements:defs.bzl", "TARGET_ARCH_VM")
load("@hrx//loom/target/amdgpu:execution_profiles.bzl", "AMDGPU_HARDWARE_PROFILE")

package(
    default_visibility = ["//visibility:private"],
    licenses = ["notice"],
)

loom_library(
    name = "rotation",
    srcs = ["rotating-views.loom"],
)

loom_test(
    name = "tests",
    srcs = ["tests.loom"],
    execution_profile = loom_execution_profile(
        name = "vm",
        build_requirements = [TARGET_ARCH_VM],
        executor = "reference",
        target_class = "cpu",
        target_family = "vm",
    ),
    deps = [":rotation"],
)

loom_kernel_library(
    name = "read_ahead",
    srcs = [
        "read-ahead.loom",
        "read-ahead-tests.loom",
    ],
    execution_profiles = [AMDGPU_HARDWARE_PROFILE],
    targets = [
        "@hrx//loom/target/amdgpu:gfx11-generic",
        "@hrx//loom/target/spirv:vulkan1.3+bda",
    ],
)
