# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# bazel-to-cmake: skip

load("@bazel_skylib//rules:common_settings.bzl", "bool_flag")

package(default_visibility = ["//visibility:public"])

bool_flag(
    name = "embed_includes",
    build_setting_default = True,
)

config_setting(
    name = "embed_includes_enabled",
    flag_values = {":embed_includes": "true"},
)
