# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("//libamdf/build_tools/bazel:cc.bzl", "amdf_cc_library")
load("//libamdf/build_tools/bazel:cts.bzl", "amdf_cts_test_suite")

package(
    default_visibility = ["//visibility:private"],
    features = ["layering_check"],
    licenses = ["notice"],  # Apache 2.0
)

amdf_cc_library(
    name = "xdna_device_fixture",
    testonly = True,
    hdrs = ["xdna_device_fixture.h"],
    deps = [
        "//libamdf/cts/util:provider_headers",
        "//third_party:google_test",
    ],
)

amdf_cc_library(
    name = "linux_tests",
    testonly = True,
    srcs = ["memory_linux_test.cc"],
    target_compatible_with = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
    ],
    deps = [
        ":xdna_device_fixture",
        "//libamdf/cts/util:provider_headers",
        "//third_party:google_test",
    ],
    alwayslink = True,
)

amdf_cc_library(
    name = "xdna_tests",
    testonly = True,
    srcs = [
        "memory_test.cc",
        "xdna_extension_test.cc",
    ],
    deps = [
        ":xdna_device_fixture",
        "//libamdf/cts/util:provider_headers",
        "//third_party:google_test",
    ] + select({
        "@platforms//os:linux": [":linux_tests"],
        "//conditions:default": [],
    }),
    alwayslink = True,
)

amdf_cts_test_suite(
    name = "xdna",
    suites = [":xdna_tests"],
    target_compatible_with = select({
        "@platforms//os:linux": [],
        "@platforms//os:windows": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    visibility = ["//visibility:public"],
)
